services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: tiangolo/nginx-rtmp
    restart: always
    ports:
      - "1935:1935"
    volumes:
      - ./streamer.conf:/etc/nginx/nginx.conf:ro
      - ./src:/usr/share/nginx/html

  streamer:
    build:
      context: .
      dockerfile: Dockerfile.streamer
    restart: always
    depends_on:
      - nginx
    networks:
      - default
      - twir
    volumes:
      - ./config.json:/app/config.json:ro
      - ./cookies.json:/app/cookies.json
    environment:
      - CHROME_URL=ws://chrome:4444/devtools/browser

networks:
  twir:
    name: twir
    external: true
