FROM node:20-slim

# Install chrome and ffmpeg
RUN apt-get update && apt-get install -y chromium ffmpeg

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

CMD ["npm", "start"]